# Generated by Django 3.1 on 2021-04-15 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_auto_20210414_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='グループ名')),
                ('icon_path', models.CharField(max_length=255, verbose_name='icon_path')),
                ('calender_path', models.CharField(max_length=255, verbose_name='calender_path')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('user_id', models.ManyToManyField(db_table='Users_Groups', to='base.Users', verbose_name='user_id')),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
