# Generated by Django 3.1 on 2021-04-18 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='グループ名')),
                ('icon_path', models.CharField(max_length=255, verbose_name='icon_path')),
                ('calender_path', models.CharField(max_length=255, verbose_name='calender_path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('user_id', models.ManyToManyField(db_table='Users_Groups', related_name='_groups_user_id_+', to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
