# Generated by Django 3.1 on 2021-04-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('follow_user_id', models.ForeignKey(blank=True, db_column='follow_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='follow_userid', to=settings.AUTH_USER_MODEL, verbose_name='follow_user_id')),
                ('followed_user_id', models.ForeignKey(blank=True, db_column='followed_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='followed_userid', to=settings.AUTH_USER_MODEL, verbose_name='followed_user_id')),
            ],
            options={
                'verbose_name_plural': 'Friends',
            },
        ),
    ]
