# Generated by Django 3.1 on 2021-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('follow_user_id', models.IntegerField(verbose_name='follow_user_id')),
                ('followed_user_id', models.IntegerField(verbose_name='followed_user_id')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('updated_at', models.DateTimeField(verbose_name='updated_at')),
            ],
        ),
    ]
