# Generated by Django 3.1 on 2021-04-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210413_2326'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterField(
            model_name='friends',
            name='follow_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_userid', to='base.users', verbose_name='follow_user_id'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='followed_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_userid', to='base.users', verbose_name='followed_user_id'),
        ),
    ]
