# Generated by Django 3.1 on 2021-04-14 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_auto_20210413_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
    ]
