# Generated by Django 3.1 on 2021-04-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210414_0113'),
        ('friend', '0005_auto_20210414_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='follow_user_id',
            field=models.ForeignKey(blank=True, db_column='follow_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='follow_userid', to='base.users', verbose_name='follow_user_id'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='followed_user_id',
            field=models.ForeignKey(blank=True, db_column='followed_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='followed_userid', to='base.users', verbose_name='followed_user_id'),
        ),
    ]
