# Generated by Django 3.1 on 2021-04-18 13:23

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(max_length=30, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='名字')),
                ('last_name_pronunciation', models.CharField(blank=True, max_length=30, null=True, verbose_name='みょうじ')),
                ('first_name', models.CharField(max_length=30, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='名前')),
                ('first_name_pronunciation', models.CharField(blank=True, max_length=30, null=True, verbose_name='なまえ')),
                ('nickname', models.CharField(blank=True, max_length=10, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='表示名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('sex', models.BinaryField(blank=True, null=True, verbose_name='性別')),
                ('mail_address', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon_path')),
                ('calendar_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='calendar_path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ResponseLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('session_id', models.CharField(max_length=255, verbose_name='session_id')),
                ('http_method', models.CharField(max_length=20, verbose_name='http_method')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('status_code', models.IntegerField(verbose_name='status_code')),
                ('text_phrase', models.CharField(max_length=255, verbose_name='text_phrase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_ID')),
            ],
            options={
                'verbose_name_plural': 'Response Logs',
            },
        ),
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('session_id', models.CharField(max_length=255, verbose_name='session_id')),
                ('http_method', models.CharField(max_length=20, verbose_name='http_method')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('user_action', models.CharField(max_length=30, verbose_name='user_action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_ID')),
            ],
            options={
                'verbose_name_plural': 'Request Logs',
            },
        ),
    ]
