# Generated by Django 3.1 on 2021-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
