# Generated by Django 3.1 on 2021-04-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nickname',
            new_name='username',
        ),
    ]
