# Generated by Django 3.1 on 2021-04-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlogs',
            options={'verbose_name_plural': 'Request Logs'},
        ),
        migrations.AlterModelOptions(
            name='responselogs',
            options={'verbose_name_plural': 'Response Logs'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users', verbose_name='user_ID'),
        ),
        migrations.AlterField(
            model_name='responselogs',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users', verbose_name='user_ID'),
        ),
    ]
