# Generated by Django 3.1 on 2021-04-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': 'Informations'},
        ),
    ]
