# Generated by Django 3.1 on 2021-05-02 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210501_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='follow_user_id',
            field=models.ForeignKey(blank=True, db_column='follow_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_userid', to=settings.AUTH_USER_MODEL, verbose_name='follow_user_id'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='followed_user_id',
            field=models.ForeignKey(blank=True, db_column='followed_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_userid', to=settings.AUTH_USER_MODEL, verbose_name='followed_user_id'),
        ),
    ]
