# Generated by Django 3.1 on 2021-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210413_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID'),
        ),
    ]
