# Generated by Django 3.1 on 2021-04-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210414_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users', verbose_name='user_ID'),
        ),
        migrations.AlterField(
            model_name='responselogs',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users', verbose_name='user_ID'),
        ),
    ]
